modLoader = "javafml"
loaderVersion = "[9,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "wylan"
version = "${version}"
displayName = "Wylan"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.wylan]]
modId = "neoforge"
type = "required"
versionRange = "[21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wylan]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wylan]]
modId = "architectury"
type = "required"
versionRange = "[17.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "wylan.mixins.json"
