name: Build
on: [pull_request, push]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.1

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v5.1.0
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      
      - name: Build
        run: ./gradlew build --stacktrace --no-daemon

      - name: Set mod version
        run: |
          awk -F'=' '/^[[:space:]]*mod_version/ {
              val=$2; gsub(/^[ \t]+|[ \t]+$/,"",val); print "MOD_VERSION=" val
            }
            /^[[:space:]]*minecraft_version/ {
              val=$2; gsub(/^[ \t]+|[ \t]+$/,"",val); print "MINECRAFT_VERSION=" val
            }
            /^[[:space:]]*archives_name/ {
              val=$2; gsub(/^[ \t]+|[ \t]+$/,"",val); print "ARCHIVES_NAME=" val
            }' $GITHUB_WORKSPACE/gradle.properties >> $GITHUB_ENV

      - name: Create package name
        run: |
          PACKAGE="${MINECRAFT_VERSION}-${ARCHIVES_NAME}-${MOD_VERSION}.zip"
          echo "package_name=${PACKAGE}" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v6.0.0
        with:
          name: ${{ env.package_name }}
          path: |
            **/build/libs/
            !build/libs/
            !**/*-dev.jar
            !**/*-shadow.jar
            !**/*-transformProduction*.jar
